### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by stevepeak**
Debugging coverage. Please do not merge. Thank you

### CODE REVIEW

**Comment by nsomar** [comment]
@stevepeak Hello, thanks for the help, did you have any luck?

**Comment by stevepeak** [comment]
@oarrabi still looks like there is no `.profdata` file created. I'm assuming you enabled the swift coverage properly: https://github.com/codecov/example-swift

I added you to our chat room to discuss more. Thanks!

**Comment by nsomar** [comment]
Hello, yes I enabled the code coverage option in the schema. Do you think it might be an issue with Xcode version.

I can see that your sample app is using Xcode7 while I am using Xcode7.1

**Comment by stevepeak** [comment]
I'll give this another shot to see where the profdata could be hiding

**Comment by stevepeak** [comment]
Are you able to produce a `profdata` file locally? If so: where is it located?

https://travis-ci.org/oarrabi/Swiftline/builds/92040469#L603

**Comment by nsomar** [comment]
I am going to close this for now :), thanks for the help

**Pull request closed without merging**
