### PR TITLE
update for Swift 2.2 compatibility

### PR DESCRIPTION
**Pull request by armcknight**
- convert Range(start:end:) to ..<
- change 'typealias' usage in AskerValidator.swift to 'associatedtype'
- [ ] update `.travis.yml` with `osx_image: xcode7.3`

### CODE REVIEW

**Comment by armcknight** [comment]
@oarrabi just mentioning you for visibility, just in case :)

**Comment by nsomar** [comment]
Hello @armcknight This looks super cool.
Could you please fix the travis error before merging?

**Comment by armcknight** [comment]
@oarrabi not sure about the code coverage thing, but it at least builds now!

**Comment by nsomar** [comment]
Yeah, The coverage never worked for this project, I will have to fix it later. 
Thanks for this update, will be merging now :)

**Pull request merged**
